import json
import os

import numpy as np
import torch

from pretty_midi import PrettyMIDI
from torch import Tensor
from torch.nn.utils.rnn import pad_sequence
from rapper import *

from mortm.models.mortm import MORTM, MORTMArgs
from mortm.models.modules.progress import _DefaultLearningProgress
from mortm.utils.generate import *
from mortm.utils.convert import MIDI2Seq
from mortm.train.tokenizer import *
from model import AbstractModelRapper


def make_system_prompt(tokenizer, key, program, call_function = None):
    prompt = [tokenizer.get("<EOS>"),
              tokenizer.get("<SYSTEM>")]

    for p in program:
        prompt.append(tokenizer.get(f"<INST_{p}>"))
    if call_function is not None:
        call_function(prompt)
    prompt.append(tokenizer.get(f"k_{key}"))
    prompt.append(tokenizer.get("<TAG_END>"))
    return np.array(prompt)

def make_system_prompt_foundation(tokenizer: Tokenizer, meta: GenerateMeta, include_dense: bool = True):
    prompt = [tokenizer.get("<EOS>"),
              tokenizer.get("<SYSTEM>")]

    for p in meta.program:
        prompt.append(tokenizer.get(f"<INST_{p}>"))
        if include_dense:
            prompt.append(tokenizer.get(f"<NOTE_DENSE_{meta.gen_note_dense[p]}>"))
    if include_dense:
        prompt.append(tokenizer.get(f"<GEN_MEASURE_COUNT_{meta.genfield_measure}>"))
    prompt.append(tokenizer.get(f"k_{meta.key}"))
    prompt.append(tokenizer.get("<TAG_END>"))
    return np.array(prompt)

class MORTM45Rapper(AbstractModelRapper):

    """MORTMモデル用の具体的な処理を実装したクラス (Concrete Strategy)"""
    def _load_model(self):
        model_path = self.meta['model_folder_path']
        config_path = os.path.join(model_path, "config.json")
        model_pth_path = os.path.join(model_path, "model.pth")

        print(f"Loading model: {self.meta['model_name']} from {model_path}")
        args = MORTMArgs(config_path)
        progress = _DefaultLearningProgress()
        model: MORTM = MORTM(args, progress).to(progress.get_device())
        model.load_state_dict(torch.load(model_pth_path), strict=False)
        model.eval() # 推論モードに設定
        return model

    def preprocessing(self, past_midi, const_midi, future_midi, meta: GenerateMeta):

        if self.meta["tag"]["model"] == "pretrained":
            tokenizer = Tokenizer(get_token_converter_pro(TO_TOKEN))
            seq = []
            print(meta.num_gems)
            
            task = getattr(meta, "task", "Prompt2MIDI")
            include_dense = task not in ["MIDI2Chord", "MetaGen"]
            
            for _ in range(meta.num_gems):
                if self.meta["tag"]["version"] == "4.5D" or self.meta["tag"]["version"] == "4.5E":
                    prompt = make_system_prompt_foundation(tokenizer, meta, include_dense=include_dense)
                else:
                    prompt = make_system_prompt(tokenizer, meta.key, meta.program)

                if task == "MIDI2Chord" or task == "MetaGen":
                    if const_midi is not None:
                        print("----CONST MIDI LOAD----")
                        const = MIDIConverter(tokenizer, os.path.dirname(const_midi), os.path.basename(const_midi), program_list=meta.program, key=meta.key)
                        const()
                        node_dict = const.midi2seq.aya_node
                        const_seq = self.get_context(tokenizer, node_dict, "<CONST_M>")
                        prompt = np.concatenate([prompt, np.array(const_seq)])
                        
                    if task == "MIDI2Chord":
                        prompt = np.concatenate([prompt, np.array([tokenizer.get("<CGEN>")])])
                    else:
                        prompt = np.concatenate([prompt, np.array([tokenizer.get("<META>")])])
                else:
                    if task == "Chord2MIDI" or getattr(meta, "chord_item", None) is not None:
                        if getattr(meta, "chord_item", None) is not None:
                            print("----CHORD LOAD----")
                            chord = MetaData2Chord(tokenizer, meta.key, meta.chord_item, meta.chord_times, meta.tempo, None, None, 999, False)
                            chord()
                            if len(chord.aya_node) > 1:
                                c = [tokenizer.get("<CONST_C>")]
                                # Use first target instrument for the chord sequence
                                target_inst = meta.program[0] if meta.program else "PIANO"
                                c.append(tokenizer.get(f"<INST_{target_inst}>"))
                                c.extend(chord.aya_node[1])
                                c.append(tokenizer.get("<ESEQ>"))
                                c.append(tokenizer.get("<TAG_END>"))
                                prompt = np.concatenate([prompt, np.array(c)])
                            else:
                                print("WARNING: No chord segments generated by MetaData2Chord")
                    
                    prompt = np.concatenate([prompt, np.array([tokenizer.get("<MGEN>")])])

                if meta.ai_continue_mode:
                    print("----AI CONTINUE MODE----")
                    past = MIDIConverter(tokenizer, os.path.dirname(past_midi), os.path.basename(past_midi), program_list=meta.program, key=meta.key)
                    past()
                    node_dict = past.midi2seq.aya_node
                    past_seq = []
                    for program, inst in node_dict.items():
                        print(inst)
                        past_seq.append(tokenizer.get(f"<INST_{program}>"))
                        past_seq.extend(inst[:-1])
                    prompt = np.concatenate([prompt, np.array(past_seq)])

                seq.append(prompt)

            return {"meta": meta, "sequence": np.array(seq), "tokenizer": tokenizer}

        elif self.meta["tag"]["model"] == "generation":
            task = getattr(meta, "task", "Prompt2MIDI")
            include_dense = task not in ["MIDI2Chord", "MetaGen"]
            
            def call(p: list):
                if include_dense:
                    p.append(tokenizer.get(f"<GEN_MEASURE_COUNT_{min(meta.genfield_measure, 8)}>"))

            tokenizer = Tokenizer(omega_converter(TO_TOKEN))
            seq = []
            for _ in range(meta.num_gems):
                prompt = make_system_prompt(tokenizer, meta.key, meta.program, call_function=call)
                if past_midi is not None:
                    print("----PAST MIDI LOAD----")
                    past = MIDIConverter(tokenizer, os.path.dirname(past_midi), os.path.basename(past_midi), program_list=meta.program, key=meta.key)
                    past()
                    node_dict = past.midi2seq.aya_node
                    past_seq = self.get_context(tokenizer, node_dict, "<PAST_M>")
                    prompt = np.concatenate([prompt, np.array(past_seq)])

                if task == "Chord2MIDI" or getattr(meta, "chord_item", None) is not None:
                    if getattr(meta, "chord_item", None) is not None:
                        print("----CHORD LOAD----")
                        chord = MetaData2Chord(tokenizer, meta.key, meta.chord_item, meta.chord_times, meta.tempo, None, None, 999, False)
                        chord()
                        c = [tokenizer.get("<CONST_C>")]
                        c.append(tokenizer.get(f"<INST_SAX>"))
                        c.extend(chord.aya_node[1])
                        c.append(tokenizer.get("<ESEQ>"))
                        c.append(tokenizer.get("<TAG_END>"))
    
                        prompt = np.concatenate([prompt, np.array(c)])

                if const_midi is not None:
                    print("----CONST MIDI LOAD----")
                    const = MIDIConverter(tokenizer, os.path.dirname(const_midi), os.path.basename(const_midi), program_list=meta.program, key=meta.key)
                    const()
                    node_dict = const.midi2seq.aya_node
                    const_seq = self.get_context(tokenizer, node_dict, "<CONST_M>")
                    prompt = np.concatenate([prompt, np.array(const_seq)])

                if future_midi is not None:
                    print("----FUTURE MIDI LOAD----")
                    future = MIDIConverter(tokenizer, os.path.dirname(future_midi), os.path.basename(future_midi), program_list=meta.program, key=meta.key)
                    future()
                    node_dict = future.midi2seq.aya_node
                    future_seq = self.get_context(tokenizer, node_dict, "<FUTURE_M>")
                    prompt = np.concatenate([prompt, np.array(future_seq)])

                if task == "MIDI2Chord":
                    prompt = np.concatenate([prompt, np.array([tokenizer.get("<CGEN>")])])
                elif task == "MetaGen":
                    prompt = np.concatenate([prompt, np.array([tokenizer.get("<META>")])])
                else:
                    prompt = np.concatenate([prompt, np.array([tokenizer.get("<MGEN>")])])
                    
                seq.append(torch.tensor(prompt).to('cuda'))

            return {"meta": meta, "sequence": seq, "tokenizer": tokenizer}


    def get_context(self, tokenizer: Tokenizer, node_dict: dict, key_token: str):
        past_seq = [tokenizer.get(key_token)]
        
        # Token ranges for chords
        cr_range = tokenizer.get_length_tuple("CR")
        cq_range = tokenizer.get_length_tuple("CQ")
        cb_range = tokenizer.get_length_tuple("CB")
        
        for program, inst in node_dict.items():
            past_seq.append(tokenizer.get(f"<INST_{program}>"))
            # Filter out chord tokens if we are providing MIDI context
            clean_inst = []
            for t_id in inst[:-1]:
                if cr_range[0] <= t_id <= cr_range[1] or \
                   cq_range[0] <= t_id <= cq_range[1] or \
                   cb_range[0] <= t_id <= cb_range[1]:
                    continue
                clean_inst.append(t_id)
            past_seq.extend(clean_inst)
            past_seq.append(tokenizer.get(f"<ESEQ>"))
        past_seq.append(tokenizer.get("<TAG_END>"))
        return past_seq


    def generate(self, **kwargs):
        meta: GenerateMeta = kwargs['meta']
        if self.meta["tag"]["model"] == "pretrained":
            np_all, pack = self.model.top_sampling_measure_kv_cache(tokenizer=kwargs["tokenizer"], src=kwargs["sequence"],
                                                     p=meta.p, temperature=meta.temperature)
            return {"meta": kwargs['meta'], "tokenizer": kwargs['tokenizer'], "sequence": pack}

        if self.meta["tag"]["model"] == "generation":
            np_all, pack = self.model.top_sampling_measure_kv_cache(tokenizer=kwargs["tokenizer"], src=pad_sequence(kwargs["sequence"], batch_first=True),
                                                     p=meta.p, temperature=meta.temperature)

            return {"meta": kwargs['meta'], "tokenizer": kwargs['tokenizer'], "sequence": pack}

    def postprocessing(self, save_directory, **kwargs):

        if self.meta["tag"]["model"] == "pretrained" or self.meta["tag"]["model"] == "generation":
            meta: GenerateMeta = kwargs['meta']
            tokenizer: Tokenizer = kwargs['tokenizer']
            tokenizer.mode(TO_MUSIC)
            sequence = kwargs['sequence']
            
            task = getattr(meta, "task", "Prompt2MIDI")
            
            outputs = []
            for i in range(len(sequence[1])):
                seq_tokens = sequence[1][i]
                
                if task == "MIDI2Chord":
                    chords = self._parse_chords(tokenizer, seq_tokens, meta.tempo)
                    outputs.append(chords)
                elif task == "MetaGen":
                    m_data = self._parse_metadata(tokenizer, seq_tokens)
                    outputs.append(m_data)
                else: 
                    output_path = os.path.join(save_directory, f"output_{i}.mid")
                    outputs.append(output_path)
                    ct_token_to_midi(tokenizer, seq_tokens, output_path, tempo=meta.tempo)
                    
            return outputs

    def _parse_chords(self, tokenizer: Tokenizer, seq, tempo: int):
        b4 = 60 / tempo
        measure = b4 * 4
        b96 = measure / 96

        measure_start_time = 0.0
        current_time = 0.0
        chords = []
        
        current_root = None
        current_quality = None
        current_bass = None
        
        def try_commit():
            nonlocal current_root, current_quality, current_bass
            if current_root is not None:
                qual = current_quality if current_quality and current_quality != "None" else ""
                bass = current_bass if current_bass and current_bass != "None" else ""
                chords.append({"time": round(current_time, 3), "chord": f"{current_root}{qual}{bass}"})
                current_root = None
                current_quality = None
                current_bass = None

        # Ensure we have a 1D sequence of token IDs
        if hasattr(seq, 'flatten'):
            seq = seq.flatten()
            
        for i, token_id in enumerate(seq):
            t_id = int(token_id.item()) if hasattr(token_id, 'item') else int(token_id)
            token = tokenizer.rev_get(t_id)
            if i < 10: print(f"DEBUG Chords token[{i}]: {token}")
            if token is None:
                continue
                
            if token == "<TE>" or token == "<EOS>" or token == "<TAG_END>":
                break
                
            if token == "<SME>":
                measure_start_time += measure
            elif token.startswith("s_"):
                try_commit()
                beat = float(token.split("_")[1])
                current_time = measure_start_time + beat * b96
            elif token.startswith("CR_"):
                current_root = token.split("_", 1)[1]
            elif token.startswith("CQ_"):
                current_quality = token.split("_", 1)[1]
            elif token.startswith("CB_"):
                current_bass = token.split("_", 1)[1]

        try_commit()
        return chords

    def _parse_metadata(self, tokenizer: Tokenizer, seq):
        meta_dict = {}
        instruments = []
        densities = {}
        current_inst = None
        # Ensure we have a 1D sequence of token IDs
        if hasattr(seq, 'flatten'):
            seq = seq.flatten()

        for i, token_id in enumerate(seq):
            t_id = int(token_id.item()) if hasattr(token_id, 'item') else int(token_id)
            token = tokenizer.rev_get(t_id)
            if i < 20: print(f"DEBUG MetaGen token[{i}]: {token}")
            if token is None:
                continue
                
            if token == "<TE>":
                break
                
            # Skip structural tokens
            if token in ("<EOS>", "<SYSTEM>", "<META>", "<MGEN>", "<CGEN>"):
                continue
                
            if token == "<TAG_END>":
                break
                
            if token.startswith("k_"):
                meta_dict["key"] = token[2:]
            elif token.startswith("<INST_"):
                current_inst = token[6:-1]
                instruments.append(current_inst)
            elif token.startswith("<NOTE_DENSE_"):
                density_val = token[12:-1]
                if current_inst:
                    densities[current_inst] = density_val
                else:
                    meta_dict["density"] = density_val
            elif token.startswith("<GEN_MEASURE_COUNT_"):
                meta_dict["gen_measure_count"] = token[19:-1]
        
        if instruments:
            meta_dict["instruments"] = instruments
        if densities:
            meta_dict["note_density"] = densities
                
        return meta_dict